// Orden de las filas en la grilla
export const CATEGORIES = [
  'Lo más visto',
  'Noticias',
  'Deportes',
  'Música',
  'Folclore',
  'Humor y charla',
  'Espectáculos',
  'Autos',
  'Campo',
  'Gaming y streamers',
  'Viajes',
  'Ciudades en vivo',
  'Paisajes y relax',
  'Cocina',
  'Hogar y obra',
  'Salud',
  'Fe',
  'Regional',
  'Infantil',
];
